python run_tracker.py -s Basketball -d  -f
python run_tracker.py -s Bolt -d  -f
python run_tracker.py -s Boy -d  -f
python run_tracker.py -s Car4 -d  -f
python run_tracker.py -s CarDark -d  -f
python run_tracker.py -s CarScale -d  -f
python run_tracker.py -s Coke -d  -f
python run_tracker.py -s Couple -d  -f
python run_tracker.py -s Crossing -d  -f
python run_tracker.py -s David -d  -f
python run_tracker.py -s David2 -d  -f
python run_tracker.py -s David3 -d  -f
python run_tracker.py -s Deer -d  -f
python run_tracker.py -s Dog1 -d  -f
python run_tracker.py -s Doll -d  -f
python run_tracker.py -s Dudek -d  -f
python run_tracker.py -s FaceOcc1 -d  -f
python run_tracker.py -s FaceOcc2 -d  -f
python run_tracker.py -s Fish -d  -f
python run_tracker.py -s FleetFace -d  -f
python run_tracker.py -s Football -d  -f
python run_tracker.py -s Football1 -d  -f
python run_tracker.py -s Freeman1 -d  -f
python run_tracker.py -s Freeman3 -d  -f
python run_tracker.py -s Freeman4 -d  -f
python run_tracker.py -s Girl -d  -f
python run_tracker.py -s Ironman -d  -f
python run_tracker.py -s Jogging-1 -d  -f
python run_tracker.py -s Jogging-2 -d  -f
python run_tracker.py -s Jumping -d  -f
python run_tracker.py -s Lemming -d  -f
python run_tracker.py -s Liquor -d  -f
python run_tracker.py -s Matrix -d  -f
python run_tracker.py -s Mhyang -d  -f
python run_tracker.py -s MotorRolling -d  -f
python run_tracker.py -s MountainBike -d  -f
python run_tracker.py -s Shaking -d  -f
python run_tracker.py -s Singer1 -d  -f
python run_tracker.py -s Singer2 -d  -f
python run_tracker.py -s Skating1 -d  -f
python run_tracker.py -s Skiing -d  -f
python run_tracker.py -s Soccer -d  -f
python run_tracker.py -s Subway -d  -f
python run_tracker.py -s Suv -d  -f
python run_tracker.py -s Sylvester -d  -f
python run_tracker.py -s Tiger1 -d  -f
python run_tracker.py -s Tiger2 -d  -f
python run_tracker.py -s Trellis -d  -f
python run_tracker.py -s Walking -d  -f
python run_tracker.py -s Walking2 -d  -f
python run_tracker.py -s Woman -d  -f
